server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: synthetic-arbitration-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: synthetic-arbitration-logs
          app: synthetic-arbitration
          level: info
          __path__: /app/logs/info/*.json
      - targets:
          - localhost
        labels:
          job: synthetic-arbitration-logs
          app: synthetic-arbitration
          level: error
          __path__: /app/logs/errors/*.json
